version = 1

[[annotations]]
path = ["BUILD.gn", "ozone_extra.gni"]
precedence = "closest"
SPDX-FileCopyrightText = "Copyright 2016 The Chromium Authors. All rights reserved."
SPDX-License-Identifier = "BSD-3-Clause"
